metaplex-foundation/aura

.env.example
nft_ingester/src/api/service.rs
nft_ingester/src/config.rs

This PR makes consistency checks on API side optional.
In devnen we cannot backfill whole the transactions history and because of that API does not return any info about some assets which are from incosistent trees, even simple getAsset may not work.
Make a few config parameters optional. Now we can even turn on only one consistency checks(if we ever need it)

MTG-374 Make consistency checks on API optional

---

nft_ingester/src/backfiller.rs
nft_ingester/src/bin/ingester/main.rs
nft_ingester/src/bin/raw_backfiller/main.rs
nft_ingester/src/config.rs
scripts/run-ingest-persisted.sh
scripts/run-slots-persisting.sh

This PR adds using BackfillSource struct to raw_backfiller
Now we can use Solana RPC in raw_backfiller. Before these changes we could use only BigTable

MTG-683 Use BackfillSource in raw_backfiller

---

rocks-db/Cargo.toml
rocks-db/src/bin/fork_detector/README.md
rocks-db/src/bin/fork_detector/main.rs

This PR adds fork cleaner tool. It's a tool we need to launch separately when indexer is turned off.
After [this PR](https://github.com/metaplex-foundation/aura/pull/258) was merged there left some assets which have updates from forked blocks. And such as changes in that PR did not fix historical data we need a separate tool which will do it.
Fork cleaner is going to detect forked data in DB and drop appropriate Merkle tree sequences. Once we do it we can launch indexer again and [SequenceConsistentGapfiller](https://github.com/metaplex-foundation/aura/blob/main/nft_ingester/src/sequence_consistent.rs#L11) will do it's job. It will find gaps in tree sequences and parse appropriate blocks to fill the gaps.

MTG-663 Add fork detector

---

metrics_utils/src/lib.rs
rocks-db/src/batch_client.rs
rocks-db/src/dump_client.rs
rocks-db/src/storage_traits.rs

This PR moves dumping fungible assets, during full synchronization, to different blocking tokio thread.
To speed up full sync process and avoid complicated selects from RocksDB.

MTG-742 Move fungible assets dump to different thread

---

entities/src/models.rs
migrations/8_token_acc_key.sql
nft_ingester/src/index_syncronizer.rs
nft_ingester/src/token_updates_processor.rs
postgre-client/src/asset_index_client.rs
postgre-client/src/load_client.rs
rocks-db/src/batch_client.rs
tests/setup/src/pg.rs

This PR adds fungible assets sync during regular synchronization. Also from now on, for fungible assets, we put two rows to index column family. And it adds new row to Postgre - asset pubkey.

MTG-747 Save updates for fungible assets during regular sync

---

nft_ingester/src/index_syncronizer.rs
rocks-db/src/batch_client.rs
rocks-db/src/dump_client.rs
rocks-db/src/storage_traits.rs
rocks-db/tests/dump_tests.rs

This PR is one more synchronizer refactor work. It adds optional hashMap to get_asset_indexes method. That map contains collection key and authority value. It's necessary only for core assets.
It should decrease number of times we query DB during asset batch processing. For full synchronization process it can save us hours(potentially).

MTG-780 Optional collection auth map

---

nft_ingester/src/mpl_core_fee_indexing_processor.rs
postgre-client/src/tasks.rs

The goal of this PR is to fix deadlocks during synchronizer work.
At the moment we have two situations with deadlocks: for core fees table, and assets with tasks.
For core fees fix is to sort valuesbefore insert.
For case with assets and tasks tables it's a bit complicated.
Such as assets table has foreign key to tasks when we insert data there transaction acquires AccessShareLock for tasks table. Then in different container we have JSON downloader which has `select ... for update` command. That command acquires ShareLock for tasks table. And here where we have a problem. Here is part of the log from Postgre: `DETAIL:  Process 720429 waits for ShareLock on transaction 52276879; blocked by process 720441.`
To fix this `FOR UPDATE` was replaced with `FOR UPDATE SKIP LOCKED`. Meaming JSON …

MTG-803 Postgre deadlocks

---

nft_ingester/src/fork_cleaner.rs
rocks-db/Cargo.toml
rocks-db/src/bin/leaf_checker/main.rs

This PR adds new Rocks CLI tool - leaf checker. Also it adds small fix to the fork cleaner.
Was found out that fork cleaner drops data from CL items for data which was not in fork, partially it happened because of missing `if` statement which this PR adds to the fork cleaner. So goal of this new tool if to find all the assets which miss it's cl_item rows and drop sequences from that updates. In other words it will create a gap in sequences which will be found and filled with `SequenceConsistentGapfiller`.
Leaf checker will be launched with stopped ingester because it requires write rights to the Rocks.

MTG-821 Add leaf checker

---

metrics_utils/src/lib.rs
nft_ingester/src/accounts_processor.rs
nft_ingester/src/bin/ingester/main.rs
nft_ingester/src/redis_receiver.rs
nft_ingester/src/transaction_processor.rs

This PR adds new metrics - MessageProcessMetricsConfig.
It will allow us to see how fast indexer process data received from Geyser plugin.
Metric call was added to main accounts and transactions processing functions. By main functions I mean functions where we extract data from Redis(or TCP connection), call processor and then call acknowledge. It means that during backfill processes that metrics will not be changed.

MTG-819 Add metrics for data processing time

---

nft_ingester/src/api/dapi/asset.rs
nft_ingester/src/api/dapi/rpc_asset_convertors.rs
nft_ingester/src/api/dapi/rpc_asset_models.rs
nft_ingester/src/processors/account_based/mpl_core_processor.rs
rocks-db/src/batch_savers.rs
rocks-db/src/token_accounts.rs

This PR fixes a few issues with Core assets.
1. If there is no authority for asset it will not return system prog adress but empty string instead.
2. For Core collections API doesn't check collection verification field.
3. If there is no collection for asset `showUnverifiedCollection` flag should not affect the API response.
4. Please take a closer look at changes in `nft_ingester/src/processors/account_based/mpl_core_processor.rs`. It was made to fix plugin ordering for assets. Kinda minor stuff so maybe we don't need it because it adds convertion from HashMap to BTreeMap during asset processing time but without that change same plugins list can be shown in different order on API side.

MTG-959 fix a few issues with core assets

---

integration_tests/Cargo.toml
integration_tests/src/account_update_tests.rs
integration_tests/src/common.rs
integration_tests/src/snapshots/integration_tests__account_update_tests__account_updates-metadata-updated.snap
integration_tests/src/snapshots/integration_tests__account_update_tests__account_updates-with-all-updates.snap
nft_ingester/src/processors/account_based/token_updates_processor.rs
rocks-db/src/lib.rs

This PR fixes `test_account_updates` integration test.
It was fixed by adding `clean_db` method and deleting `chain_mutability` value update during Mint account processing. It was always set it to `Mutable` and it was kinda mistake because it affected NFTs where mutability property if defined at Metadata account, not Mint.
All other tests were not affected by these changes.

MTG-993 Fix one integration test

---

backfill_rpc/src/rpc.rs
nft_ingester/src/processors/transaction_based/bubblegum_updates_processor.rs
nft_ingester/src/processors/transaction_processor.rs
nft_ingester/src/transaction_ingester.rs
rocks-db/src/transaction_client.rs
usecase/src/signature_fetcher.rs

Before we had `confirmed` data streamed to us from the Geyser plugin, `confirmed` signatures fetched by the relevant worker and `finalized` slots ingested from the slot persister. The signature fetcher confirmation level doesn't seem to add any value, as most transactions are streamed by the Geyser anyway. Switching signature fetcher to finalized level of commitment allows us to define data ingested from signature fetcher as finalized and resolve cNFT forks using signature fetchers.

[MTG-1066] using finalized level for signature fetcher

---

metrics_utils/src/lib.rs

defining the buckets for the indexing lag with a wider and more appropriate range

[MTG-1072] improving indexing lag visibility 

---

Cargo.lock
Cargo.toml
nft_ingester/Cargo.toml
nft_ingester/src/bin/explorer/main.rs
nft_ingester/src/bin/explorer/readme.md

Explorer is a small RESTful service built in Rust that allows you to interact with a RocksDB database. It provides endpoints to:
- **Iterate over keys** in a specified column family.
- **Retrieve the value** for a specific key.
Both keys and values are Base58-encoded for safe transmission over HTTP.
- [Explorer](#explorer)
- [Table of Contents](#table-of-contents)
- [Features](#features)
- [Prerequisites](#prerequisites)
- [Building the Project](#building-the-project)
- [Running the Service](#running-the-service)
- [Optional Arguments](#optional-arguments)
- [Example with all arguments:](#example-with-all-arguments)
- [Configuration](#configuration)
- [API Endpoints](#api-endpoints)
- [Iterate Keys](#iterate-keys)
- [Example Request:](#example-request)
- [Get Value](#get-value)
- [Example …

a small rocks-db explorer for debugging purposes

---

.github/workflows/rust.yml
backfill_rpc/src/slots_collector.rs
ingester.Dockerfile
integrity_verification.Dockerfile
metrics_utils/src/utils.rs
nft_ingester/Cargo.toml
nft_ingester/src/api/service.rs
nft_ingester/src/api/synchronization_state_consistency.rs
nft_ingester/src/backfiller.rs
nft_ingester/src/bin/slot_persister/main.rs
nft_ingester/src/plerkle.rs
nft_ingester/src/scheduler.rs
nft_ingester/tests/batch_mint_test.rs
postgre-client/src/asset_filter_client.rs
postgre-client/src/asset_index_client.rs
postgre-client/src/integrity_verification_client.rs
postgre-client/src/lib.rs
postgre-client/src/tasks.rs
rocks-db/src/clients/batch_client.rs
rocks-db/src/column.rs
rocks-db/src/columns/asset.rs
rocks-db/src/generated/mod.rs
rocks-db/src/migrator.rs
rust-toolchain.toml
usecase/src/proofs.rs

This PR updates base Docker images to use Rust 1.84, and consequently handles clippy errors stemming from the new Rust version.

MTG-1176: fix docker builds & update Rust version to 1.84.0

---

entities/src/models.rs
nft_ingester/tests/api_tests.rs

Stop trimming whitespace in the name and metadata of assets to prevent invalid indexing.

[mtg-1162] URI trimming

---

postgre-client/src/asset_filter_client.rs
postgre-client/tests/asset_filter_client_test.rs
postgre-client/tests/asset_index_client_test.rs
rocks-db/src/column.rs
rocks-db/src/columns/asset.rs
rocks-db/src/sequence_consistent.rs
tests/setup/src/pg.rs

The PR optimizes the search request via dropping OR condition if a search for all token types is requested. OR condition in such case provokes seq scan through the table. 
To avoid this, UNION between two selects is used instead.

[mtg-808] optimize select for show fungible display option

---

nft_ingester/tests/api_tests.rs

Given 10 asset updates in nft asset index and empty pg database (last_synchronized_key = null)
When index cleaner is called
Then all 10 updates should be present in asset_update_idx
Given 10 asset updates in nft updates index and last_synchronized_key = 5…. for nfts
When index cleaner is called
Then 4 update records should be removed

[mtg-1036] tests for asset index cleaner

---

metrics_utils/src/lib.rs
nft_ingester/src/bin/ingester/main.rs
nft_ingester/src/config.rs
nft_ingester/src/message_parser.rs
nft_ingester/src/redis_receiver.rs

NOTE! This PR also adds filename and line number printing to all logs emitted using `tracing::error!/info!/debug!/trace!`. This is in line with the configuration of the `log` crate we use, but nevertheless important to mention here.
The rest of the PR adds metrics describing the lifecycle of `RedisReceiver`.

feat(ingester): add metrics for `RedisReceiver`

---

integration_tests/src/snapshots/integration_tests__account_update_tests__account_updates-metadata-updated.snap
integration_tests/src/snapshots/integration_tests__account_update_tests__account_updates-token-updated.snap
integration_tests/src/snapshots/integration_tests__account_update_tests__account_updates-with-all-updates.snap
integration_tests/src/snapshots/integration_tests__account_update_tests__account_updates.snap
integration_tests/src/snapshots/integration_tests__general_scenario_tests__asset_parsing.snap
integration_tests/src/snapshots/integration_tests__regular_nft_tests__reg_get_asset.snap
integration_tests/src/snapshots/integration_tests__regular_nft_tests__reg_get_asset_batch-2-and-a-missing-1.snap
integration_tests/src/snapshots/integration_tests__regular_nft_tests__reg_get_asset_batch-only-2-different-2.snap
integration_tests/src/snapshots/integration_tests__regular_nft_tests__reg_get_asset_batch-only-2.snap
integration_tests/src/snapshots/integration_tests__regular_nft_tests__reg_get_asset_by_group.snap
integration_tests/src/snapshots/integration_tests__regular_nft_tests__reg_search_assets.snap
integration_tests/src/snapshots/integration_tests__regular_nft_tests__regular_nft_collection.snap
nft_ingester/src/api/dapi/rpc_asset_convertors.rs

This PR extends range of interfaces for which we display `supply` object on API response. Basicaly there were added more interfaces which may have edition information which could be put into `supply` object.
From the changes in snapshots of integration tests we can see what is changing for the user.

MTG 1235 Extend range of interfaces for supply object display

---

interface/src/json.rs
nft_ingester/src/api/dapi/asset.rs
nft_ingester/src/bin/api/main.rs
nft_ingester/src/bin/ingester/main.rs
nft_ingester/src/bin/slot_checker/main.rs
nft_ingester/src/config.rs
nft_ingester/src/json_worker.rs
nft_ingester/tests/api_tests.rs

As a short-term solution for longer requests we disable the cache invalidation alongside the request.
Also we separate the inline json download timeout from the main workers timeout, letting workers wait for 30 seconds for the response, while the inline download is restricted to 3 seconds.

[MTG-1258] an option to turn off the json re-download, enabled by default

---

rocks-db/src/migrations/clitems_v2.rs
rocks-db/src/migrations/offchain_data.rs
rocks-db/src/migrator.rs
rocks-db/tests/migration_tests.rs

The previous rocks migration changed the structure of Change Log Items, as well as the key encoding, putting the tree before the index, and thus keeping all tree-related change logs together, rather than dispersed. But the migration was putting the data using the old encoding of the keys, thus rendering invalid keys and no data after the migration. This did not affect the newly added data, or the backfilled data, but the migration itself. 
This change allows preserving the data by properly migrating it.

[MTG-1266] hotfix for migrations when the key encoding changes

---

migrations/11_owner_index.sql

migration to add an appropriate index for queries with owner as those are always sorted by smth 
Previously the index used for getAssetByOwner was planned as
```
Limit  (cost=0.70..2570578.36 rows=1000 width=49) (actual time=72.449..2881.472 rows=1000 loops=1)"
"  ->  Index Scan Backward using assets_pkey on assets_v3  (cost=0.70..3148777688.88 rows=1224930 width=49) (actual time=0.807..2809.575 rows=1000 loops=1)"
"        Filter: ((ast_supply > 0) AND (ast_owner = '\x000be3e1eba17a473f89b0f7e8e24940f20aeb8ebca71a88fde95d4b83b71a09'::bytea))"
"        Rows Removed by Filter: 602490"
"Planning Time: 0.936 ms"
"JIT:"
"  Functions: 6"
"  Options: Inlining true, Optimization true, Expressions true, Deforming true"
"  Timing: Generation 1.355 ms, Inlining 11.620 ms, Optimization 39.588 ms, …
```

[MTG-1166] Changing owner index to speed up owner based requests

---

nft_ingester/src/redis_receiver.rs

This PR fixes counting redis_total_accounts_parsed metric. The issue is that value is incremented by `result.len()` but if `self.message_parser.parse_account(item.data, false)` returns empty vector we don't write anything to the `result` vec, but message was processed by fact. Parse_account method may return empty vector if it received account with program owner which we don't support. So as a result of this issue we can see not very informative metric on Grafana - `Unparsed Transactions & Accounts`, which looks like ingester cannot parse all the data, but it's wrong, we see it only because values in metric were not calculated correctly. It didn't happen before because previous Solana snapshot ETL was using Geyser plugin  which has accounts filter inside and it sent only accounts which …

MTG 1289 Fix redis_total_accounts_parsed metric

---

Cargo.lock
ingester.Dockerfile
nft_ingester/Cargo.toml
nft_ingester/src/api/dapi/change_logs.rs
rocks-db/src/clients/asset_streaming_client.rs
rocks-db/src/columns/cl_items.rs
rocks-db/src/sequence_consistent.rs
rocks-db/tests/parameters_tests.rs

Handling data in Aura is challenging due to several factors:
- **Forked Data:**  
Data received from forks is treated as non-finalized, which can lead to uncertainty.
- **Missed Slots:**  
Occasionally, we miss a slot when fetching slots with bubblegum transactions, causing valid pending data to be overlooked as finalized.
- **Delayed Slot Fetching:**  
Some slots are fetched with significant delays (beyond a couple of minutes), complicating timely processing.
- **Concurrent Update Processing:**  
When processing a batch of updates in a slot concurrently, some merges may be missed. This is a potential major issue that warrants further investigation.
To address these challenges, we now store **two versions** of the change log items and their hashes:
- **Most Recent Non-Finalized Data:** …

[MTG-1151] finding valid proof when there are alternatives

---

.github/workflows/rust.yml

Enable CI for develop branch PRs
- Update GitHub Actions workflow to run on PRs targeting develop branch
- Maintain same CI checks for both main and develop branches
- Ensure code quality standards are enforced before merging to develop

ci: enable CI for develop branch PRs

---

.github/workflows/docker.yml

- Separate metadata generation for tag and branch builds to prevent invalid tags.
- Ensure correct tagging format for `latest`, `branch-latest`, and `semver`.
- Improve version extraction logic.

[OBEZS] Fix Docker tag generation for branch and tag builds

---

entities/src/api_req_params.rs
nft_ingester/src/api/builder.rs
nft_ingester/tests/api_tests.rs

Two things are changed in this PR:
1) V1 payload parsing is prioritized over V0 as for V0 we do not parse `displayOptions` at all.
2) `showUnverifiedCollections` now defaults to `false`.

feat(api): rework payload parsing

---

nft_ingester/Cargo.toml
nft_ingester/src/bin/burnt_assets_ingester/main.rs

This PR adds a new binary tool for ingesting burnt assets from a JSON file into RocksDB. 
- Add new binary tool burnt_assets_ingester for processing burnt assets from JSON file
- Implement Asset to AssetCompleteDetails conversion with full field mapping
- Add batch processing with configurable batch size for efficient storage 
- Add error handling and logging for better observability 
- Add comprehensive test coverage with multiple test cases 
- Added unit tests covering different asset scenarios 
- Tested with sample data for various asset types 
- Verified batch processing and error handling 
- Added command-line arguments documentation 
- Included code comments explaining the conversion logic 
- Closes #MTG-1194

[MTG-1194] Add burnt assets ingester tool

---

.github/workflows/docker.yml
.github/workflows/release-finalize.yml
.github/workflows/release-prepare.yml
Cargo.lock
Makefile
RELEASE_PROCESS.md
cliff.toml
nft_ingester/Cargo.toml

This PR implements a fully automated release process using GitHub Actions. The process is triggered manually and handles all steps from creating a release branch to publishing Docker images and bumping the development version.
**Workflow Overview**
The release process is split into two main workflows:
1.  **`release-prepare.yml`:**
*   Triggered manually via `workflow_dispatch` with the desired release version (e.g., `0.5.0`).
*   Creates a `release/vX.Y.Z` branch from `develop`.
*   Updates version numbers in `Cargo.toml` and other relevant files.
*   Generates a `CHANGELOG.md` file using `git-cliff` based on Conventional Commits.
*   Creates a pull request from the release branch to `main`.
*   Uploads the generated changelog as an artifact.
2.  **`release-finalize.yml`:**
*   Triggered …

[MTG-1360] release process

---

.github/workflows/release-prepare.yml

- Fix changelog generation in release-prepare.yml:
- Remove invalid --strip header,footer parameter and use --strip all instead
- Remove --config flag when cliff.toml might not exist
- Add warning message when cliff.toml is missing

[MTG-1360] fix(ci): resolve issues with release workflows

---

Cargo.lock
integration_tests/src/regular_nft_tests.rs
nft_ingester/Cargo.toml
nft_ingester/docker-compose_db.yml
nft_ingester/src/api/dapi/rpc_asset_convertors.rs
nft_ingester/tests/api_tests.rs

- Return empty string for all collection_metadata fields if we have no values

[mtg-1380] fix(api):  getAssetsByCreator doesn't return empty fields

---

entities/src/api_req_params.rs
nft_ingester/tests/api_tests.rs

Move the `token_type` field in `SeachAssets` to the end of the struct in order to not break pagination on V0 representation (positional JSON case).
This is a **breaking change** for users of positional JSON of V1 variant, but positional JSON seems to not be publicly used outside of umi.

fix(api): reorder `SearchAssets` fields to comply with V0 repr

---

CHANGELOG.md
Cargo.lock
backfill_rpc/Cargo.toml
cliff.toml
consistency_check/Cargo.toml
entities/Cargo.toml
grpc/Cargo.toml
integration_tests/Cargo.toml
integrity_verification/Cargo.toml
interface/Cargo.toml
metrics_utils/Cargo.toml
nft_ingester/Cargo.toml
postgre-client/Cargo.toml
rocks-db/Cargo.toml
tests/setup/Cargo.toml
usecase/Cargo.toml

This PR merges changes from the v0.6.0 release into develop and bumps the version to 0.6.1-dev.

Merge v0.6.0 release back to develop and bump version

---

nft_ingester/src/index_synchronizer.rs
rocks-db/src/clients/batch_client.rs

- Add MAX_SEQUENCE_GAP constant (1M) to control sequence gap threshold
- Modify fetch_fungible_asset_updated_keys and fetch_nft_asset_updated_keys to:
- Get highest sequence from up_to or database
- Continue processing if gap exceeds MAX_SEQUENCE_GAP
- Log warning when large gap is detected
- Preserve existing behavior for smaller gaps

feat(synchronizer): allow continuation of sync on large sequence gaps [MTG-1215]
